### ISSUE TITLE
Create Navbar

### ISSUE THREAD

**Issue by STrojann** [STrojann/Gym-Genius#1]
Create navbar with styling that renders tabs to the page.

**Comment by SK-ILLish-GIT** [comment]
Dear @STrojann ,

I am writing to request that you assign me the task of creating a Navbar. I believe I am well-suited for this task, and I am confident that I can complete the job to the best of my abilities.

Thank you for your time and consideration.

**Comment by STrojann** [comment]
> 



> Dear @STrojann ,
> 
> I am writing to request that you assign me the task of creating a Navbar. I believe I am well-suited for this task, and I am confident that I can complete the job to the best of my abilities.
> 
> Thank you for your time and consideration.

Hello hope you all well,

This project is for my University boot camp and I have been assigned a group for this. However, I would like to say if you would like to work on a project in the future together I would be happy to do so. Thank you
